name: SnowTerritory
version: '${project.version}'
main: top.arctain.snowTerritory.Main
api-version: '1.21'
authors: [ Arctain ]
website: www.arctain.top
depend: [ MMOItems ]
softdepend: [ Vault, PlayerPoints ]
commands:
  snowterritory:
    description: SnowTerritory 主命令
    usage: /snowterritory <子命令>
    aliases: [sn]
    permission: mmoitemseditor.use
permissions:
  mmoitemseditor.use:
    description: 允许使用 SnowTerritory 命令
    default: op
  mmoitemseditor.edit:
    description: 允许使用物品编辑功能
    default: op
  mmoitemseditor.reload:
    description: 允许重载插件配置
    default: op
  mmoitemseditor.itemid:
    description: 允许查看物品ID
    default: op

