name: SnowTerritory
version: '${project.version}'
main: top.arctain.snowTerritory.Main
api-version: '1.21'
authors: [ Arctain ]
website: www.arctain.top
depend: [ MMOItems ]
softdepend: [ Vault, PlayerPoints ]
commands:
  edititem:
    description: 打开物品强化编辑界面
    usage: /edititem
    permission: mmoitemseditor.edit
    permission-message: 您没有权限使用此命令！
  reloadeditor:
    description: 重载插件配置
    usage: /reloadeditor
    permission: mmoitemseditor.reload
    permission-message: 您没有权限使用此命令！
permissions:
  mmoitemseditor.edit:
    description: 允许使用物品编辑功能
    default: op
  mmoitemseditor.reload:
    description: 允许重载插件配置
    default: op

